# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PLj7KK5mUfIAJ7kX7Zfxh4TN2nWT6ZI
"""

import pandas as pd
df = pd.read_csv('train.csv')

df.head()

from IPython.display import HTML

html_code = """
<h1> 1. Categorical Data </h1>
<h2> a. CountPlot </h2>
"""

HTML(html_code)

import seaborn as sns

sns.countplot(x='Survived', data=df)
#df['Survived'].value_counts().plot(kind='bar') It works like count plot only means count the value of categories and implementing
#bar chart on it

sns.countplot(x='Pclass', data=df)

sns.countplot(x='Sex', data=df)

sns.countplot(x='Embarked', data=df)

from IPython.display import HTML

html_code = """
<h2> b. PieChart </h2>
"""

HTML(html_code)

df['Survived'].value_counts().plot(kind='pie', autopct='%.2f')

df['Pclass'].value_counts().plot(kind='pie', autopct='%.2f')

df['Sex'].value_counts().plot(kind='pie', autopct='%.2f%%')

from IPython.display import HTML

html_code = """
<h1> 1. Numerical Data </h1>
<h2> a. Histogram </h2>
"""

HTML(html_code)

import matplotlib.pyplot as plt

plt.hist(df['Age'])
# #plt.hist(df['Age'], bins=50)

# The bins parameter in histograms defines how data is grouped into intervals,
# or "bins", to create the visual representation of the data distribution

# Each bin represents a range of values, and the height of the
# bar corresponds to the number of data points falling within that range

from IPython.display import HTML

html_code = """
<h2> b. Distplot </h2>
"""

HTML(html_code)

# sns.distplot(df['Age']) # Deprecated
sns.displot(df['Age'], kde=True)
# ecdf : empirical cumulative distribution function
# kde : kernel density estimation is a line on displot which shows the the distribution of data

# displot() method is a function that provides access to several approached for visualizing univariate and bivariate distribution of data.
# This function like other functions in the Seaborn library allows the plotting
# of subsets of data defined by semantic mapping across multiple subplots.

#displots also helps to calculate skewness

from IPython.display import HTML

html_code = """
  <h2> c. Box Plot </h2>
"""

HTML(html_code)

sns.boxplot(df['Fare']) # Box Plot is used to identify noise or outliers in data

sns.boxplot(df['Age'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()

df2 = pd.read_csv('twb.csv') #T20 Batting dataset

df2.head()

sns.countplot(x='100', data=df2)

df2['100'].value_counts().plot(kind='pie', autopct='%.2f%%')

plt.hist(df2['Inns'])

sns.displot(df2['6s'], kde=True)

sns.boxplot(df2['4s'])

