# -*- coding: utf-8 -*-
"""ML_Practice_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113928RjzPFKYH3W96-KQi_leF3W3fJDC
"""

import numpy as np
from sklearn import linear_model

n_samples, n_features = 1, 500

y = np.random.randn(n_samples)
X = np.random.randn(n_samples, n_features)

clf = linear_model.SGDRegressor()

import time

start_time = time.time()

clf.partial_fit(X,y)

elapsed_time = time.time() - start_time

print(elapsed_time)

y = np.random.randn(n_samples)
X = np.random.randn(n_samples, n_features)

clf.partial_fit(X,y)