# -*- coding: utf-8 -*-
"""ML_Practice3 ( Understanding the Data ).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-qoCu1Uwx8MX5b48DBK7uuOT4tsk-fi
"""

import pandas as pd

df = pd.read_csv('train.csv')

# How Big is the Data
df.shape

# How does the Data look like
# df.head()
df.sample(5) # It give random rows from dataset Syntax : df.sample(no_of_rows)

# What is the Data Type of Cols
df.info()

# Optimisation tricks on datasets means alot as it reduce storage, improve performance etc
# Ex : Convert Age column to integer

# Are there any missing values
df.isnull().sum() # Gives the total number of missing values of each collumn

# How does the data look Mathematically
df.describe()

# Are there duplicate values
df.duplicated().sum() # Returns the total number of duplicate rows

# How is the correlation between cols
df.select_dtypes(include='number').corr()

df.select_dtypes(include='number').corr()['Survived']

