# -*- coding: utf-8 -*-
"""ML_Practice : Web Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPAW_xyR4XVQoPpEPUDf6W8d8b6twaX6
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

url = 'https://books.toscrape.com/'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
}

try:
    response = requests.get(url, headers=headers, timeout=10)
    response.raise_for_status()
    webpage = response.text
    print("Page fetched successfully.")
except requests.exceptions.RequestException as e:
    print("Error fetching the page:", e)

soup = BeautifulSoup(webpage, 'lxml') #It is used to parse html of webpage
print(soup.prettify())

print(soup.find_all('p')[1].text) # find_all is used to find tags mentioned you can also used find method
print(soup.find_all('h1')[0].text) #[index] used to retrive that specific tag if there are more than one tag
print(soup.find_all('h3')[0].text) #.text is used tp retrieve text of it

for i in soup.find_all('h3'):
  print(i.text.strip()) # Strip function is used to remove space or \n after text

for i in soup.find_all('p', class_="price_color"): #class_ is used to scrape specific p text of defined class
  print(i.text.strip())

print(len(soup.find_all('p', class_="price_color")))
print(len(soup.find_all('h3')))

books = soup.find_all('li',class_="col-xs-6 col-sm-4 col-md-3 col-lg-3") # Assigning all books in that web page which are there in that specific tag and class

len(books)

names = []
prices = []

for i in books:
  names.append(i.find('h3').text.strip())
  prices.append(i.find('p',class_="price_color").text.strip())

names

prices

df = pd.DataFrame({'Book Name':names,'Book Price':prices})
print(df)

url = 'https://books.toscrape.com/catalogue/page-1.html'
final_df = pd.DataFrame()
for i in range(1,10):
  url = f'https://books.toscrape.com/catalogue/page-{i}.html'
  soup = BeautifulSoup(webpage, 'lxml')
  books = soup.find_all('li',class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

  names = []
  prices = []

  for j in books:
    try:
      names.append(j.find('h3').text.strip())
    except:
      names.append(np.nan) #If there is no data available in that case append Nan
    try:
      prices.append(j.find('p',class_="price_color").text.strip())
    except:
      prices.append(np.nan)

    df = pd.DataFrame({'Book Name':names,'Book Price':prices})

    final_df = pd.concat([final_df,df],ignore_index=True) #Used to concat or merge or append two data frames

final_df

