# -*- coding: utf-8 -*-
"""ML :- Pandas_Profiler (ydata ).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZOCCrKXdYWTdkhbEF_wEq6-OsHYyscD
"""

import pandas as pd
import seaborn as sns

titanic = pd.read_csv('train.csv')
tips = sns.load_dataset('tips')
flights = sns.load_dataset('flights')

df.sample(5)

pip install pandas-profiling

pip install --upgrade numba

pip install ydata-profiling

from ydata_profiling import ProfileReport
prof = ProfileReport(titanic)
prof.to_file('Titanic_Dataset_Report.html')


# It automatically analyzes your entire DataFrame and creates a detailed exploratory data analysis (EDA) report in HTML format.

# What’s inside the report?
# Overview

# Number of variables (columns), observations (rows), missing cells, duplicate rows, etc.

# Variables (Column-wise summary)

# Interactions

# Correlations

# Missing Values

# Visualizations showing patterns of missing data, heatmaps, and counts.

# Warnings & Alerts

prof = ProfileReport(tips)
prof.to_file('Tips_Dataset_Report.html')

prof = ProfileReport(flights)
prof.to_file('Flights_Dataset_Report.html')

