# -*- coding: utf-8 -*-
"""ML Practice 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnepLUtQhrn30krcwnwNgdEiWiu6QZFP
"""

import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)
# np.random.seed() sets the "seed" for NumPy's pseudo-random number generator.
# By setting it to 42 (which is a common convention, famously from "The Hitchhiker's Guide to the Galaxy," but any integer would work),
# you ensure that every time you run this code, the sequence of "random" numbers generated by NumPy will be exactly the same.

# Create data
data = {
    'Unnamed: 0': np.arange(1, 51),
    'CGPA': np.round(np.random.uniform(1.0, 10.0, 50), 2),
    'IQ': np.random.randint(20, 180, 50),
    'Placement': np.random.randint(0, 2, 50)
}

# Create DataFrame
df = pd.DataFrame(data)

# Show first few rows
print(df.head())

df = df.iloc[:,1:]
print(df.head())

#Steps

#0. Preprocess + EDA + Feature Selection
#1. Extract Input and Output Columns
#2. Train Test Split
#3. Scale the values
#4. Train the Model
#5. Evaluate the model/ model Selection
#6. Deploy the Model

df.shape

import matplotlib.pyplot as plt

plt.scatter(df['CGPA'],df['IQ'],c=df['Placement'])

#CGPA and IQ are independent variables and Placement is Dependent Variables

x = df.iloc[:,0:2] # Seperates CGPA and IQ column and assign it to x
y = df.iloc[:,-1] # Seperates Placement Column and assign it to y

from sklearn.model_selection import train_test_split
# The train_test_split() method is used to split our data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.1) #Test_size = 0.1 means 10% data we will go in test and remaining 90% in training

# Syntax: sklearn.model_selection.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None


# Parameters:


# *arrays: sequence of indexables. Lists, numpy arrays, scipy-sparse matrices, and pandas dataframes are all valid inputs.
# test_size: int or float, by default None. If float, it should be between 0.0 and 1.0 and represent the percentage of the dataset to test split. If int is used, it refers to the total number of test samples. If the value is None, the complement of the train size is used. It will be set to 0.25 if train size is also None.
# train_size: int or float, by default None.
# random_state : int,by default None. Controls how the data is shuffled before the split is implemented. For repeatable output across several function calls, pass an int.
# shuffle: boolean object , by default True. Whether or not the data should be shuffled before splitting. Stratify must be None if shuffle=False.
# stratify: array-like object , by default it is None. If None is selected, the data is stratified using these as class labels.

# Returns:


# splitting: The train-test split of inputs is represented as a list.

from sklearn.preprocessing import StandardScaler # Scaling

scaler = StandardScaler() # Scaling the data
#  StandardScaler is a feature scaling technique which follows Standard Normal Distribution (SND)
#  and is used to standardize the values of numeric features. It transforms data so that the mean becomes 0
#  and the standard deviation becomes 1. It’s ideal for algorithms like SVM, logistic regression
#  or neural networks that assume data is normally distributed

x_train = scaler.fit_transform(x_train) # Nethod is used to scale the data

x_train

x_test = scaler.transform(x_test) # Nethod is used to scale the data if you already understand pattern in ouput ex Placement 0 and 1 only

x_test

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression() # Classifier

clf.fit(x_train,y_train) # Training the model, fit method is used to train the data

# Evaluate the model
y_pred = clf.predict(x_test) # Predicting Accuracy

y_pred

y_test

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred) # Calculating Accuracy in this out of 5 Test samples it gives 3 are correct others are incorrect

from mlxtend.plotting import plot_decision_regions # Used to draw Decision Boundary

plot_decision_regions(x_train,y_train.values,clf = clf,legend=2) # y_train.values ensures that the class labels are passed to the plotting function in the expected NumPy array format.
# x_train was already in numpy array format

