# -*- coding: utf-8 -*-
"""ML :- Bivariate/Multivariate Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5kZVOKPffdn6g3vAVlHld1MLCzGH-Ax
"""

import seaborn as sns
import pandas as pd

tips = sns.load_dataset('tips')
titanic = pd.read_csv('train.csv')
flights = sns.load_dataset('flights')
iris = sns.load_dataset('iris')

tips.head()

flights.head()

iris.head()

from IPython.display import HTML

html_code = """
<h1> 1. ScatterPlot ( Numerical - Numerical) </h1>
"""
HTML(html_code)

sns.scatterplot(data=tips, x='total_bill', y='tip') # Bivariate Analyis

sns.scatterplot(data=tips, x='total_bill', y='tip', hue=tips['sex']) # Multivariate Analysis
#On three Columns

sns.scatterplot(data=tips, x='total_bill', y='tip', hue=tips['sex'], style=tips['smoker']) #Multivariate Analysis
# On four Columns

sns.scatterplot(data=tips, x='total_bill', y='tip', hue=tips['sex'], style=tips['smoker'], size=tips['size']) #Multivariate Analysis
# On five Columns

from IPython.display import HTML

html_code = """
<h1> 2. Barplot ( Numerical - Categorical) </h1>
"""
HTML(html_code)

sns.barplot(x='Pclass',y='Age', data=titanic) # On x axis we put categorical data
 #on y axis numerical quantity
# Bivariate Analysis

sns.barplot(x='Pclass',y='Fare', data=titanic)

sns.barplot(x='Pclass',y='Age', hue='Sex', data=titanic)

sns.barplot(x='Pclass',y='Fare', hue='Sex', data=titanic)

html_code = """
<h1> 3. Boxplot ( Numerical - Categorical) </h1>
"""
HTML(html_code)

sns.boxplot(x='Sex', y='Age',data=titanic, hue="Survived")

html_code = """
<h1> 4. Displot ( Numerical - Categorical) </h1>
"""
HTML(html_code)

sns.displot(titanic[titanic['Survived']==0]['Age'], kde=True)
sns.displot(titanic[titanic['Survived']==1]['Age'], kde=True)

from IPython.display import HTML

html_code = """
<h1> 5. HeatMap (Categorical - Categorical) </h1>
"""
HTML(html_code)

sns.heatmap(pd.crosstab(titanic['Pclass'], titanic['Survived'])) # It gives categorical class relation table

titanic.groupby('Pclass').mean(numeric_only=True)['Survived']*100 # This is the percentage of number of people survived

#In this we groupby Pclass and then calculate mean of those who survived in that specific class

titanic.groupby('Sex').mean(numeric_only=True)['Survived']*100 # This is the percentage of number of people survived

titanic.groupby('Embarked').mean(numeric_only=True)['Survived']*100 # This is the percentage of number of people survived

html_code = """
<h1> 6. ClusterMap (Categorical - Categorical) </h1>
"""
HTML(html_code)

sns.clustermap(pd.crosstab(titanic['Parch'], titanic['Survived']))

html_code = """
<h1> 7. Pairplot</h1>
"""
HTML(html_code)

sns.pairplot(iris)
# Seaborn's pairplot() is used to visually explore relationships between multiple numerical variables in a dataset.
# Its like how every numerical feature is related to every other one

sns.pairplot(iris, hue='species') # It is representing three different species

html_code = """
<h1> 8. Lineplot ( Numerical - Numerical ) </h1>
"""
HTML(html_code)

#Seaborn's lineplot() is used to visualize trends over continuous or ordered data using a line.
# Data which is related to time, date means it si increasing or decreasing with respect to them

flights.dtypes

flights['year'] = flights['year'].astype(int)
newdf = flights.groupby('year')['passengers'].sum().reset_index()
flights.groupby('year')['passengers'].sum().reset_index()
# Group the data by year, sum the number of passengers for each year,
# and reset the index to convert the result into a proper DataFrame for further use (like plotting)

sns.lineplot(data=newdf, x='year', y='passengers')

flights.pivot_table(index='month', columns='year', values='passengers')

sns.heatmap(flights.pivot_table(index='month', columns='year', values='passengers'))

sns.clustermap(flights.pivot_table(index='month', columns='year', values='passengers'))

