# -*- coding: utf-8 -*-
"""Tensors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMlAGtBxOVvv1vBmS_1TpwK86mrrMGNx
"""

import numpy as np

a = np.array(4) #1D Tensor/ Scalar
print("Array : ",a)
print("No of Dimensions : ",a.ndim)

a = np.array([1,2,3,4]) #2D Tensor/ Vectors
print("Array : ",a)
print("No of Dimensions : ",a.ndim)

a = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3D Tensor/ Matrices
print("Array : ",a)
print("No of Dimensions : ",a.ndim)

